# TreasureChests Configuration

# The chance (out of 1.0) that a treasure chest will drop when a valid block is broken.
# For example, 0.05 is a 5% chance.
drop-chance: 0.05

# A list of blocks that can drop a treasure chest when broken.
allowed-blocks:
  - "STONE"
  - "DEEPSLATE"
  - "DIORITE"
  - "ANDESITE"
  - "GRANITE"

# loot-tables defines the loot found in treasure chests.
loot-tables:
  # 'rolls' determines how many times the plugin tries to add an item to the chest.
  rolls: "3-5"

  # Tiers define the different types of treasure chests that can be found.
  tiers:
    common:
      display-name: "&aGewöhnliche Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.50
      despawn-timer: 60
      broadcast-enabled: false
      broadcast-message: "&6&lSCHATZFUND! &e%player% &7hat eine &e%tier% &7Schatztruhe gefunden!"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: false
      animations:
        spawn:
          sound: { name: "ENTITY_PLAYER_LEVELUP", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "IRON_INGOT"
          amount: "5-10"
          chance: 0.8
        - material: "BREAD"
          amount: "3-5"
          chance: 1.0
        - material: "COAL"
          amount: "4-8"
          chance: 0.9
      xp_boost:
        enabled: true
        modifier: 1.5
        duration: 300
    rare:
      display-name: "&9Seltene Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.25
      despawn-timer: 120
      broadcast-enabled: false
      broadcast-message: "&6&lSCHATZFUND! &e%player% &7hat eine &e%tier% &7Schatztruhe gefunden!"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: false
      animations:
        spawn:
          sound: { name: "ENTITY_PLAYER_LEVELUP", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "GOLDEN_APPLE"
          amount: 1
          chance: 0.7
        - material: "DIAMOND"
          amount: "1-3"
          chance: 0.5
        - material: "IRON_PICKAXE"
          amount: 1
          chance: 0.4
      xp_boost:
        enabled: true
        modifier: 2.0
        duration: 600
    epic:
      display-name: "&5Epische Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.15
      despawn-timer: 180
      broadcast-enabled: true
      broadcast-message: "&6&lSCHATZFUND! &e%player% &7hat eine &e%tier% &7Schatztruhe gefunden!"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: true
      animations:
        spawn:
          sound: { name: "ENTITY_PLAYER_LEVELUP", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "DIAMOND_SWORD"
          amount: 1
          chance: 0.4
        - material: "TOTEM_OF_UNDYING"
          amount: 1
          chance: 0.2
        - material: "EXPERIENCE_BOTTLE"
          amount: "8-16"
          chance: 0.8
      xp_boost:
        enabled: true
        modifier: 2.5
        duration: 900
    legendary:
      display-name: "&6Legendäre Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.08
      despawn-timer: 240
      broadcast-enabled: true
      broadcast-message: "&6&lSCHATZFUND! &e%player% &7hat eine &e%tier% &7Schatztruhe gefunden!"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: true
      animations:
        spawn:
          sound: { name: "ENTITY_PLAYER_LEVELUP", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "NETHERITE_INGOT"
          amount: "1-2"
          chance: 0.3
        - material: "ELYTRA"
          amount: 1
          chance: 0.1
        - material: "BEACON"
          amount: 1
          chance: 0.05
      xp_boost:
        enabled: true
        modifier: 3.0
        duration: 1200
    mythical:
      display-name: "&dMythische Kiste"
      head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Y2NmY3ZjAzMTI1Y2Y1NDczMzY5NmYzNjMyZjBkOWU2NDcwYmFhYjg0OTg0N2VhNWVhMmQ3OTE1NmFkMGY0MCJ9fX0="
      chance: 0.02
      despawn-timer: 300
      broadcast-enabled: true
      broadcast-message: "&6&lSCHATZFUND! &e%player% &7hat eine &e%tier% &7Schatztruhe gefunden!"
      sound:
        name: "ENTITY_PLAYER_LEVELUP"
        broadcast: true
      animations:
        spawn:
          sound: { name: "ENTITY_PLAYER_LEVELUP", volume: 0.5, pitch: 1.5 }
          particles:
            - { type: "CLOUD", count: 15, speed: 0.05 }
          scale: { from: 0.1, to: 2.8, duration: 10 }
        despawn:
          particles:
            - { type: "SMOKE_NORMAL", count: 15, speed: 0.05 }
          scale: { from: 2.8, to: 0.0, duration: 10 }
      items:
        - material: "NETHER_STAR"
          amount: 1
          chance: 0.2
        - material: "ENCHANTED_GOLDEN_APPLE"
          amount: 1
          chance: 0.1
        - material: "DRAGON_EGG"
          amount: 1
          chance: 0.01
      xp_boost:
        enabled: true
        modifier: 4.0
        duration: 1800
# Custom items
items:
  luck_boosters:
    common:
      display-name: "&fGewöhnlicher Glücks-Booster"
      lore:
        - "&7Erhöht die Chance auf Schätze für 10 Minuten."
      multiplier: 1.5
      duration: 600
    rare:
      display-name: "&9Seltener Glücks-Booster"
      lore:
        - "&7Erhöht die Chance auf Schätze für 10 Minuten."
      multiplier: 2.0
      duration: 600
    epic:
      display-name: "&5Epischer Glücks-Booster"
      lore:
        - "&7Erhöht die Chance auf Schätze für 10 Minuten."
      multiplier: 2.5
      duration: 600
    legendary:
      display-name: "&6Legendärer Glücks-Booster"
      lore:
        - "&7Erhöht die Chance auf Schätze für 10 Minuten."
      multiplier: 3.0
      duration: 600
  golden_pickaxe:
    display-name: "&6Legendäre Spitzhacke"
    lore:
      - "&7Garantiert eine legendäre Kiste."
      - "&7Nur eine Benutzung."
    enchantments:
      - "EFFICIENCY:5"
